repository: 
  auto_init: true
  has_issues: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true

branches:
 - name: default
   protection:
     required_pull_request_reviews:
      required_approving_review_count: 3
      require_code_owner_reviews: true
     enforce_admins: false
     required_status_checks: null
     restrictions: null
